// APP
export const PURGE = 'PURGE';
export const SET_APP_WALLETS = 'SET_APP_WALLETS';

// WALLET
export const SET_WALLET_TRANSACTIONS = 'SET_WALLET_TRANSACTIONS';
export const SET_WALLET_TOKENS = 'SET_WALLET_TOKENS';

// TOKENS
export const SET_TOKEN_PAIRS = 'SET_TOKEN_PAIRS';
