// APP
export const PURGE = 'PURGE';

// WALLET
export const SET_WALLET = "SET_WALLET";
export const SET_WALLET_ETHEREUM_TOKENS = 'SET_WALLET_ETHEREUM_TOKENS';
export const SET_WALLET_ETHEREUM_TRANSACTIONS = 'SET_WALLET_ETHEREUM_TRANSACTIONS';
export const SET_WALLET_ARBITRUM_TOKENS = 'SET_WALLET_ARBITRUM_TOKENS';
export const SET_WALLET_ARBITRUM_TRANSACTIONS = 'SET_WALLET_ARBITRUM_TRANSACTIONS';

// GROUP
export const SET_GROUP = 'SET_GROUP';

// TOKENS
export const SET_TOKEN_PAIRS = 'SET_TOKEN_PAIRS';
